export interface User {
  first_name: string,
  last_name: string,
  email_address: string,
  gender: string,
  annual_income: number,
  occupation_industry: string,
  location: string,
  birthday: string,
  age: number,
  primary_language: string,
  family_status: string,
  average_annual_spending: number,
  current_total_debt: number,
  owns_home: boolean,
  owns_vehicle: boolean,
}